const fs = require("fs");
const path = require("path");

const appName = "shipfast-node";
const artifactType = "s3-static-web";
const deploymentTarget = "amazon-s3-static-website";

const rootDir = path.resolve(__dirname, "..");
const distDir = path.join(rootDir, "dist");
const webDir = path.join(distDir, "web");

const packageJsonPath = path.join(rootDir, "package.json");
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));

const packageVersion = packageJson.version || "1.0.0";

const buildVersion = process.env.VERSION || packageVersion;
const releaseTag = process.env.RELEASE_TAG || "local-build";
const commitSha = process.env.GITHUB_SHA || "local";
const shortSha = commitSha.substring(0, 7);
const buildTime = new Date().toISOString();

fs.mkdirSync(webDir, { recursive: true });

const health = {
  app: appName,
  status: "ok",
  artifact_type: artifactType,
  deployment_target: deploymentTarget,
  build_version: buildVersion,
  release_tag: releaseTag,
  commit_sha: commitSha,
  short_sha: shortSha,
  generated_at: buildTime
};

const version = {
  app: appName,
  package_version: packageVersion,
  build_version: buildVersion,
  release_tag: releaseTag,
  commit_sha: commitSha,
  short_sha: shortSha,
  artifact_type: artifactType,
  deployment_target: deploymentTarget,
  generated_by: "github-actions-node-ci",
  generated_at: buildTime
};

const deploymentInfo = {
  app: appName,
  package_version: packageVersion,
  build_version: buildVersion,
  release_tag: releaseTag,
  commit_sha: commitSha,
  short_sha: shortSha,
  artifact_type: artifactType,
  deployment_target: deploymentTarget,
  note: "Generated during CI. CD workflow can enrich this with environment-specific deployment metadata.",
  generated_at: buildTime
};

const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ShipFast Node Web App</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <main class="page">
    <section class="card">
      <div class="eyebrow">Production Grade CI/CD with GitHub Actions</div>
      <h1>ShipFast Node Web App</h1>
      <p class="subtitle">Static web artifact generated by Node CI and deployed through GitHub Actions CD.</p>

      <div class="grid">
        <div class="item">
          <span class="label">Application</span>
          <span class="value">${appName}</span>
        </div>
        <div class="item">
          <span class="label">Artifact Type</span>
          <span class="value">${artifactType}</span>
        </div>
        <div class="item">
          <span class="label">Deployment Target</span>
          <span class="value">${deploymentTarget}</span>
        </div>
        <div class="item">
          <span class="label">Build Version</span>
          <span class="value">${buildVersion}</span>
        </div>
        <div class="item">
          <span class="label">Release Tag</span>
          <span class="value">${releaseTag}</span>
        </div>
        <div class="item">
          <span class="label">Commit SHA</span>
          <span class="value">${shortSha}</span>
        </div>
      </div>

      <div class="links">
        <a href="./health.json">Health JSON</a>
        <a href="./version.json">Version JSON</a>
        <a href="./deployment-info.json">Deployment Info</a>
      </div>
    </section>
  </main>
</body>
</html>
`;

const errorHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ShipFast Node Web App - Error</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <main class="page">
    <section class="card">
      <div class="eyebrow">ShipFast Node Web App</div>
      <h1>Page Not Found</h1>
      <p class="subtitle">The requested static page was not found.</p>
      <div class="links">
        <a href="./index.html">Back to Home</a>
      </div>
    </section>
  </main>
</body>
</html>
`;

const stylesCss = `:root {
  --bg: #07132b;
  --panel: #f4f8fc;
  --card: #ffffff;
  --text: #0d1b33;
  --muted: #6b7c99;
  --blue: #0055cc;
  --green: #007a60;
  --purple: #5a3fa0;
  --line: #d6e2f0;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
  background: linear-gradient(135deg, var(--bg), #10264d);
  color: var(--text);
}

.page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
}

.card {
  width: 100%;
  max-width: 980px;
  background: var(--card);
  border-radius: 18px;
  padding: 36px;
  box-shadow: 0 18px 50px rgba(0, 0, 0, 0.25);
}

.eyebrow {
  color: var(--blue);
  font-size: 14px;
  font-weight: 700;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  margin-bottom: 12px;
}

h1 {
  margin: 0;
  font-size: 38px;
  line-height: 1.15;
}

.subtitle {
  color: var(--muted);
  font-size: 17px;
  margin: 12px 0 28px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
  margin-bottom: 30px;
}

.item {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 12px;
  padding: 16px;
}

.label {
  display: block;
  color: var(--muted);
  font-size: 13px;
  margin-bottom: 6px;
}

.value {
  display: block;
  color: var(--text);
  font-size: 15px;
  font-weight: 700;
  word-break: break-word;
}

.links {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.links a {
  display: inline-block;
  text-decoration: none;
  color: #ffffff;
  background: var(--blue);
  padding: 11px 16px;
  border-radius: 10px;
  font-weight: 700;
}

.links a:nth-child(2) {
  background: var(--green);
}

.links a:nth-child(3) {
  background: var(--purple);
}

@media (max-width: 720px) {
  .grid {
    grid-template-columns: 1fr;
  }

  h1 {
    font-size: 30px;
  }
}
`;

fs.writeFileSync(path.join(webDir, "index.html"), indexHtml);
fs.writeFileSync(path.join(webDir, "error.html"), errorHtml);
fs.writeFileSync(path.join(webDir, "styles.css"), stylesCss);
fs.writeFileSync(path.join(webDir, "health.json"), JSON.stringify(health, null, 2));
fs.writeFileSync(path.join(webDir, "version.json"), JSON.stringify(version, null, 2));
fs.writeFileSync(path.join(webDir, "deployment-info.json"), JSON.stringify(deploymentInfo, null, 2));

console.log("Static web build completed.");
console.log(`Output directory: ${webDir}`);
console.log("Generated files:");

for (const file of fs.readdirSync(webDir)) {
  console.log(`- ${file}`);
}