name: Demo

on:
  push:
    branches:
      - dev

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Node.js Setup
        uses: actions/setup-node@v6
        with:
          node-version: '20'    
        
      
      
      






          