name: demo

on:
    push:
        branches:
            - dev

jobs:
    demo:
      name: Demo Job
      runs-on: ubuntu-latest

      steps:
        - name: Code checkout
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.14'
            
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'    

