name: Reusable Workflow Demo

on:
  push:
    branches:
      - dev
      - stage
    paths:
      - "app/node/**"
      - ".github/workflows/reusable_workflow_demo.yml"
      - ".github/workflows/reusable-ci.yml"
      - ".github/workflows/reusable-cd.yml"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/reusable-ci.yml
    secrets: inherit

  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/reusable-cd.yml
    with:
      environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
      image_version: ${{ needs.ci.outputs.image_version }}
    secrets: inherit