name: Reusable Workflow Demo

on:
  push:
    branches: [dev, stage, main]
    paths:
      - "app/node/**"
      - ".github/workflows/reusable_workflow_demo"

permissions:
  contents: read
  id-token: write
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/reusable-ci.yml
    secrets: inherit

  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/reusable-cd.yml
    with:
      # dev -> dev, stage -> stage, main -> prod
      environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    secrets: inherit